-- 1 films
CREATE TABLE IF NOT EXISTS  films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    description varchar(100),
    release_date date,
    duration integer
);

-- 2
CREATE TABLE IF NOT EXISTS ganre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

-- 3
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100),
    login varchar(100),
    name varchar(100),
    birthday date
);

-- 4
CREATE TABLE IF NOT EXISTS film_rating(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    category varchar(100)
);

-- 5
CREATE TABLE IF NOT EXISTS film_likes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    user_id INTEGER REFERENCES users
);

-- 6
CREATE TABLE IF NOT EXISTS film_ganre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    ganre_id INTEGER REFERENCES ganre
);

-- 7
CREATE TABLE IF NOT EXISTS friends(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users,
    friend_id INTEGER REFERENCES users,
    approved boolean
);

