-- 1 films
CREATE TABLE IF NOT EXISTS  films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    description varchar(100),
    release_date date,
    duration integer
);

-- 2
CREATE TABLE IF NOT EXISTS genre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

INSERT INTO genre (id, name)
SELECT 1, 'Комедия'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Комедия'
);

INSERT INTO genre (id, name)
SELECT 2, 'Драма'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Драма'
);

INSERT INTO genre (id, name)
SELECT 3, 'Мультфильм'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Мультфильм'
);

INSERT INTO genre (id, name)
SELECT 4, 'Триллер'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Триллер'
);

INSERT INTO genre (id, name)
SELECT 5, 'Документальный'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Документальный'
);

INSERT INTO genre (id, name)
SELECT 6, 'Боевик'
WHERE NOT EXISTS (
    SELECT 1
    FROM genre
    WHERE genre.name = 'Боевик'
);
-- 3
CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(100),
    login varchar(100),
    name varchar(100),
    birthday date
);

-- 4
CREATE TABLE IF NOT EXISTS mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)
);

INSERT INTO mpa (id, name)
SELECT 1, 'G'
WHERE NOT EXISTS (
    SELECT 1
    FROM mpa
    WHERE mpa.name = 'G'
);

INSERT INTO mpa (id, name)
SELECT 2, 'PG'
WHERE NOT EXISTS (
    SELECT 2
    FROM mpa
    WHERE mpa.name = 'PG'
);

INSERT INTO mpa (id, name)
SELECT 3, 'PG-13'
WHERE NOT EXISTS (
    SELECT 3
    FROM mpa
    WHERE mpa.name = 'PG-13'
);

INSERT INTO mpa (id, name)
SELECT 4, 'R'
WHERE NOT EXISTS (
    SELECT 4
    FROM mpa
    WHERE mpa.name = 'R'
);

INSERT INTO mpa (id, name)
SELECT 5, 'NC-17'
WHERE NOT EXISTS (
    SELECT 5
    FROM mpa
    WHERE mpa.name = 'NC-17'
);

-- 5
CREATE TABLE IF NOT EXISTS film_likes(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    user_id INTEGER REFERENCES users
);

-- 6
CREATE TABLE IF NOT EXISTS film_genre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    genre_id INTEGER REFERENCES genre
);

CREATE TABLE IF NOT EXISTS film_mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films,
    mpa_id INTEGER REFERENCES mpa
);

-- 7
CREATE TABLE IF NOT EXISTS friends(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users,
    friend_id INTEGER REFERENCES users,
    approved boolean
);

